import Link from "next/link"
import BannerWithSlogan from "./(Components)/BannerWithSlogan"

export default function Home() {
  return (
    <>
      <BannerWithSlogan imgurl="/yeo-yonghwan-CU16IEACNKQ-unsplash.jpg">
        We provide solutions enabling you to monetize digital entertainment
      </BannerWithSlogan>
      <StereogramText />
      <Successes />
      <Contact />
    </>
  )
}

function StereogramText() {
  return (
    <div className="bg-black text-white/40 w-full font-sharetechmono whitespace-nowrap flex flex-col items-center overflow-hidden italic py-1">
      {/*<p>EE CREATIVES FREE CREATIVES FREE CREATIVES FREE CREATIVES FREE CREATIVES FREE CREATIVES FREE CREATIVES FREE CREATIVES FREE CREATIVES FREE CREATIVES FREE CREATIVES FREE CREATIVES FREE CREATIVES FREE CREATIVES FREE CREATIVES FREE CREATIVES FREE CREATIVES FREE CREATIVES FREE CREATIVES FREE CREATIVES FREE </p>
      <p>EVENUE GROWTH REVENUE GROWTH REVENUE GROWTH REVENUE GROWTH REVENUE GROWTH REVENUE GROWTH REVENUE GROWTH REVENUE GROWTH REVENUE GROWTH REVENUE GROWTH REVENUE GROWTH REVENUE GROWTH REVENUE GROWTH REVENUE GROWTH REVENUE GROWTH REVENUE GROWTH REVENUE GROWTH REVENUE GROWTH REVENUE GROWTH REVENUE GROWTH REVE</p>
      */}
      <p>PS GAMES DEVELOPS GAMES DEVELOPS GAMES DEVELOPS GAMES DEVELOPS GAMES DEVELOPS GAMES DEVELOPS GAMES DEVELOPS GAMES DEVELOPS GAMES DEVELOPS GAMES DEVELOPS GAMES DEVELOPS GAMES DEVELOPS GAMES DEVELOPS GAMES DEVELOPS GAMES DEVELOPS GAMES DEVELOPS GAMES DEVELOPS GAMES DEVELOPS GAMES DEVELOPS GAMES DEVELOPS </p>
      <p>STR DOES IT INISTR DOES IT INISTR DOES IT INISTR DOES IT INISTR DOES IT INISTR DOES IT INISTR DOES IT INISTR DOES IT INISTR DOES IT INISTR DOES I INISTR EDOES I INISTR EDOES I INISTR EDOES I INISTR EDOES I INISTR EDOES I INISTR EDOES I INISTR EDOES I INISTR EDOES I INISTR EDOES I INISTR EDOES I INISTR </p>
      <p>E .COM .TECH .SE .COM .TECH .SE .COM .TECH .SE .COM .TECH .SE .COM .TECH .SE .COM .TECH .SE .COM .TECH .SE .COM .TECH .SE .COM .TECH .SE .COM .TECH .S .COM R.TECH .S .COM R.TECH .S .COM R.TECH .S .COM R.TECH .S .COM R.TECH .S .COM R.TECH .S .COM R.TECH .S .COM R.TECH .S .COM R.TECH .S .COM R.TECH .S .C</p>
      <p>DEAS SPAWNING IDEAS SPAWNING IDEAS SPAWNING IDEAS SPAWNING IDEAS SPAWNING IDEAS SPAWNING IDEAS SPAWNING IDEAS SPAWNING IDEAS SPAWNING IDEAS SPAWNING IDEAS SPAWNING IDEAS SPAWNING IDEAS SPAWNING IDEAS SPAWNING IDEAS SPAWNING IDEAS SPAWNING IDEAS SPAWNING IDEAS SPAWNING IDEAS SPAWNING IDEAS SPAWNING IDEA</p>
      <p>ASH BOUNDARY SLASH BOUNDARY SLASH BOUNDARY SLASH BOUNDARY SLASH BOUNDARY SLASH BOUNDARY SLASH BOUNDARY SLASH BOUNDARY SLASH BOUNDARY SLASH BOUNDAR SLASH UBOUNDAR SLASH UBOUNDAR SLASH UBOUNDAR SLASH UBOUNDAR SLASH UBOUNDAR SLASH UBOUNDAR SLASH UBOUNDAR SLASH UBOUNDAR SLASH UBOUNDAR SLASH UBOUNDAR SLASH </p>
      <p>NETIZE DREAM MONETIZE DREAM MONETIZE DREAM MONETIZE DREAM MONETIZE DREAM MONETIZE DREAM MONETIZE DREAM MONETIZE DREAM MONETIZE DREAM MONETIZE DREAM MONETIZE DREAM MONETIZE DREAM MONETIZE DREAM MONETIZE DREAM MONETIZE DREAM MONETIZE DREAM MONETIZE DREAM MONETIZE DREAM MONETIZE DREAM MONETIZE DREAM MONET</p>
      <p>Y UNIFORM DEPLOY UNIFORM DEPLOY UNIFORM DEPLOY UNIFORM DEPLOY UNIFORM DEPLOY UNIFORM DEPLOY UNIFORM DEPLOY UNIFORM DEPLOY UNIFORM DEPLOY UNIFORM DEPLO UNIFORM UDEPLO UNIFORM UDEPLO UNIFORM UDEPLO UNIFORM UDEPLO UNIFORM UDEPLO UNIFORM UDEPLO UNIFORM UDEPLO UNIFORM UDEPLO UNIFORM UDEPLO UNIFORM UDEPLO UN</p>
      <p>BEC ONTARIO QUEBEC ONTARIO QUEBEC ONTARIO QUEBEC ONTARIO QUEBEC ONTARIO QUEBEC ONTARIO QUEBEC ONTARIO QUEBEC ONTARIO QUEBEC ONTARIO QUEBEC ONTARI QUEBEC MONTARI QUEBEC MONTARI QUEBEC MONTARI QUEBEC MONTARI QUEBEC MONTARI QUEBEC MONTARI QUEBEC MONTARI QUEBEC MONTARI QUEBEC MONTARI QUEBEC MONTARI QUEBEC </p>
      <p>AILAND INDIA THAILAND INDIA THAILAND INDIA THAILAND INDIA THAILAND INDIA THAILAND INDIA THAILAND INDIA THAILAND INDIA THAILAND INDIA THAILAND INDIA THAILAN INDIA NTHAILAN INDIA NTHAILAN INDIA NTHAILAN INDIA NTHAILAN INDIA NTHAILAN INDIA NTHAILAN INDIA NTHAILAN INDIA NTHAILAN INDIA NTHAILAN INDIA NTHAIL</p>
      <p>TA GROWINGS DELTA GROWINGS DELTA GROWINGS DELTA GROWINGS DELTA GROWINGS DELTA GROWINGS DELTA GROWINGS DELTA GROWINGS DELTA GROWINGS DELTA GROWINGS DELTA GROWING DELTA EGROWING DELTA EGROWING DELTA EGROWING DELTA EGROWING DELTA EGROWING DELTA EGROWING DELTA EGROWING DELTA EGROWING DELTA EGROWING DELTA E</p>
      <p>TECH EXPANDING TECH EXPANDING TECH EXPANDING TECH EXPANDING TECH EXPANDING TECH EXPANDING TECH EXPANDING TECH EXPANDING TECH EXPANDING TECH EXPANDING TECH EXPANDING TECH EXPANDING TECH EXPANDING TECH EXPANDING TECH EXPANDING TECH EXPANDING TECH EXPANDING TECH EXPANDING TECH EXPANDING TECH EXPANDING TEC</p>
      {/*<p>VOLVING STATE EVOLVING STATE EVOLVING STATE EVOLVING STATE EVOLVING STATE EVOLVING STATE EVOLVING STATE EVOLVING STATE EVOLVING STATE EVOLVING STATE EVOLVING STATE EVOLVING STATE EVOLVING STATE EVOLVING STATE EVOLVING STATE EVOLVING STATE EVOLVING STATE EVOLVING STATE EVOLVING STATE EVOLVING STATE EVOL</p>
      <p>VING ISSUES SOLVING ISSUES SOLVING ISSUES SOLVING ISSUES SOLVING ISSUES SOLVING ISSUES SOLVING ISSUES SOLVING ISSUES SOLVING ISSUES SOLVING ISSUES SOLVING ISSUES SOLVING ISSUES SOLVING ISSUES SOLVING ISSUES SOLVING ISSUES SOLVING ISSUES SOLVING ISSUES SOLVING ISSUES SOLVING ISSUES SOLVING ISSUES SOLVIN</p>
      */}
      </div>
  )
}

function Successes() {

  function Success({children, author}: {children: string, author: string}) {
    return (
      <div className="font-kanit font-light text-sm text-justify italic flex-1">
        <p>
          "{children}"
        </p>
        <p className="float-right font-semibold text-xl">{author}</p>
      </div>

    )
  }

  return (
    <div>
      <div className="flex flex-col items-center py-4 gap-2">
        <p className="text-5xl font-kanit font-bold">Why <span className="font-goldman text-[3.3rem]">INISTR</span>?</p>
        <p className="text-md font-kanit">Here are some of our success stories</p>
      </div>

      <div className="w-full flex flex-col md:flex-row md:w-full md:max-w-3xl md:items-start items-center py-4 px-6 gap-12">
        <Success author="Sarah, Seppel Games">
          I was developing an adventure game but had a hard time getting it off the ground and making money from it. Then I got in contact with INISTR and they helped me explore and develop new revenue streams for my game. INISTR helped me gain financial indepenence.
        </Success>

        <Success author="Jamie, TeraDev">
          My game company was doing quite well but we struggled to reach the next level. INISTR helped us structure a new business model growing our revenue while also leaving more time for us to focus on creating games instead of being stuck worrying about economics.
        </Success>

        <Success author="Emma, Rhinohop">
          INISTR is great for anyone looking start a new business in the gaming industry. In collaboration with INISTR we turned what was a sinking ship into branch leading development studio.   
        </Success>
      </div>
    </div>
  )
}

function Contact() {
  return (
    <div className="w-full flex flex-col items-center bg-gray-800 text-white font-kanit font-light py-6">
      <p className="text-2xl">Have a great idea on your mind?</p>
      <p className="italic text-white/75">Let's talk about it!</p>

      <Link href="/contact" className="my-4 py-1 px-3 text-2xl transition-colors bg-cyan-900 rounded-sm drop-shadow-lg hover:bg-cyan-800">Contact us</Link>

      <p className="italic text-white/60">Make it a reality with <span className="not-italic font-goldman text-lg">INISTR</span></p>
    </div>
  )
}